services:
  fastapi-redis:
    image: redis:latest
    container_name: fastapi-redis
    env_file:
      - .env
    ports:
      - 6379:6379
    networks:
      - fastapi-network

  fastapi-neo4j:
    image: neo4j:latest
    container_name: fastapi-neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4j
    ports:
      - 7474:7474
      - 7687:7687
    restart: always
    volumes:
      - neo4j_data:/data
    networks:
      - fastapi-network

  fastapi-chromadb:
    image: chromadb/chroma
    container_name: fastapi-chromadb
    environment:
      - CHROMA_SERVER_AUTHN_CREDENTIALS=admin:$$2y$$05$$K4zk4e9Ep8T6nfnKilxD5euOa6speUJxyegGm21/Y34h5EjOOpNwa
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.basic_authn.BasicAuthenticationServerProvider
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    ports:
      - 8000:8000
    volumes:
      - chroma_data:/chroma/chroma
    restart: always
    networks:
      - fastapi-network

volumes:
  neo4j_data:
  chroma_data:

networks:
  fastapi-network:
    driver: bridge
