services:
  fastapi-redis:
    image: redis:latest
    container_name: fastapi-redis
    env_file:
      - .env
    ports:
      - 6379:6379

  fastapi-neo4j:
    image: neo4j:latest
    container_name: fastapi-neo4j
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
    restart: always
    volumes:
      - neo4j_data/data:/data
      - neo4j_data/logs:/logs
      - neo4j_data/config:/config
      - neo4j_data/plugins:/plugins

volumes:
  neo4j_data:
    name: fastapi-neo4j-data
